name: MATCH ON NORTH
favicon: null
layout_spectrum: 0.3404240917880088
typography_spectrum: 0.7964997438248247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4211916115600616
  lightness: 0.5968849945347756
  saturation: 0.8700726791284978
  rhythmicContrast: 0.9813134323339909
purpose: []
